### ISSUE TITLE
ZIP 密码在线破解无法起到破解的作用

### ISSUE THREAD

**Issue by Steve5wutongyu6** [chaitin/xtools#75]
![image](https://github.com/chaitin/xtools/assets/77491648/622db919-df79-4cf0-8e87-3f292f923a92)
[arasaka.zip](https://github.com/chaitin/xtools/files/13791159/arasaka.zip)
正确的解压密码是14748478，而无论如何修改密码字符集，程序始终输出“破解成功，密码是 aaaa25”。密码不仅没破解成功，“aaaa”也不包含在我指定的密码字符集中

**Comment by Steve5wutongyu6** [comment]
换了个小一点的文件试了下，貌似也不行
[1.zip](https://github.com/chaitin/xtools/files/13791198/1.zip)
正确密码也是14748478
![image](https://github.com/chaitin/xtools/assets/77491648/569c5ebf-f34e-4b22-beb3-4440f57a195e)

**Comment by safe1ine** [comment]
用了fcrack的快速破解算法，这个算法确实有可能输出错误的密码，尤其是压缩包里文件数量越少，错误的可能性越大。
我来解决一下吧

**Comment by safe1ine** [comment]
@Steve5wutongyu6 修好了,看这里
https://github.com/chaitin/xtools/pull/81

**Comment by Steve5wutongyu6** [comment]
> @Steve5wutongyu6 修好了,看这里 #81

试了下，已经没有问题了
![image](https://github.com/chaitin/xtools/assets/77491648/b8812f00-91e7-4367-9171-9886732dd691)
